# Generated by Django 3.2 on 2021-06-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210604_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'required': 'This field cannot be blank,the max digits are 100 and must be unique'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(error_messages={'required': 'This field cannot be blank and the max digits are 50'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(error_messages={'required': 'This field cannot be blank and the max digits are 50'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'required': 'This field cannot be blank, the max digits are 50 and must be unique'}, max_length=100, unique=True),
        ),
    ]
